apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: cloudbowl
spec:
  kafka:
    version: 3.1.0
    replicas: 3
    listeners:
#    - name: external
#      port: 9094
#      tls: false
#      type: loadbalancer
    - name: plain
      port: 9092
      type: internal
      tls: false
    config:
      auto.create.topics.enable: "false"
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.4"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
